import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image"
import Header from "./_components/header/header";
import Footer from "./_components/footer/footer";
import { AuthProvider } from "./_context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className={"mainContainer"}>
            <div className="mainSection">
              <Header />
              <main className={"mainContentSection"}>
                {children}
              </main>
              <div className="bottomButtonSection">
                <Image src={"/paper_folding.svg"} alt="bottom button" width={60} height={80}/>
              </div>
            </div>
            <Footer/>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
