import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={"mainContainer"}>
          <header className={"header"}>
            <h1>PageDay</h1>
            <nav>
              <Link href="/login">로그인</Link>
              <Link href="/signup">회원가입</Link>
            </nav>
          </header>
          <main className={"main"}>
            {children}
          </main>
          <footer className={"footer"}>
            &copy; 2024 PageDay
          </footer>
        </div>
      </body>
    </html>
  );
}
